// Framing for the USB link to the harness daemon — turns a byte stream into messages, and messages back
// into bytes.
//
// The mirror image of cli/src/cable/cableFrame.ts in the autonomous-harness repository. Both halves are
// checked against ONE shared vector file (test/vectors/cable_frame.txt, generated by
// scripts/gen_cable_vectors.py from the format description rather than from either implementation), so a
// shared misreading shows up as a disagreement instead of being blessed by both. The two halves live in
// two repositories and cannot import each other; the vectors are the only thing they share.
//
// Wire format, little-endian throughout:
//
//   A5 5A | ver:u8 | type:u8 | len:u16 | payload[len] | crc16:u16
//
// The magic is what the reader scans for after losing its place; the CRC is what separates a real frame
// from two bytes of noise that happened to look like the magic. That matters more here than on most
// links, and for a reason specific to this board: it has exactly ONE USB port (measured — it enumerates
// as 303a:1001 and nothing else), so the console and this protocol share a wire. The ROM, the
// second-stage bootloader and the panic handler all write plain text to it, and the reader on the other
// end walks into the middle of a stream at every boot.
//
// That is also why CABLE_TYPE_LOG exists: with a type byte, an ESP_LOG line is just another frame rather
// than something the reader has to guess at. Only what the firmware cannot route — ROM chatter, a panic
// dump — arrives as bare text, and the decoder steps over it a byte at a time and counts it.
//
// DELIBERATELY FREE OF ESP-IDF. This file compiles with a plain host compiler, which is how
// test/test_cable_frame.c runs the shared vectors on a laptop in milliseconds instead of on the device
// through a flash cycle.
#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// ⚠️ THE SECOND BYTE NAMES THE PRODUCT, AND IT IS NOT DECORATION.
//
// This board is also the board a SIBLING product ships — same 466x466 round panel, same
// ESP32-S3, and so the same USB identity (303a:1001, a ROM peripheral whose descriptor cannot be changed
// without giving up the console this port also carries). Its firmware speaks a protocol descended from
// the same ancestor as this one: same framing, and a `hello` carrying the same three fields under the
// same names. Nothing on the wire told the two apart.
//
// What that cost: the sibling's updater flashes a panel whose version differs from the one in its bundle
// — in EITHER direction, its own spec says so — so plugging a Harness dial into a machine running that
// app hands the dial over within seconds. It cannot be talked out of it from this side, because it is
// acting on a `hello` it was able to read.
//
// So the two are made mutually unintelligible at the first byte pair. A decoder scanning for its own
// magic never matches the other's frames, never obtains a `hello`, never learns a version, and therefore
// never offers firmware. This is the one protection that works WITHOUT the other product changing
// anything; every other layer needs both sides to cooperate.
//
// 0xA5 leads because it is outside ASCII — the ROM, the bootloader and the panic handler write plain text
// to this same wire, and a magic that could occur in that text would resync the decoder onto garbage.
// 0x48 is 'H'. The sibling takes 'G'. Read a hex dump and the frame says whose it is.
#define CABLE_MAGIC_0 0xA5
#define CABLE_MAGIC_1 0x48   // 'H' — Harness. The sibling product uses a different second byte.

// Bumped only when the ENVELOPE changes. The message vocabulary inside carries its own version in the
// `hello` handshake, so adding a message is not a framing change and must not bump this.
#define CABLE_FRAME_VERSION 1

#define CABLE_HEADER_BYTES 6   // magic(2) + ver(1) + type(1) + len(2)
#define CABLE_CRC_BYTES    2

// A bound on damage, not a capacity target: the largest thing this link sends in one piece is a firmware
// slice. A corrupt length field can claim up to 65535 bytes, and with no ceiling the reader would sit
// waiting for a frame that is never coming while real frames pile up behind it — a hang, not a dropped
// message.
#define CABLE_MAX_PAYLOAD 8192

#define CABLE_MAX_FRAME (CABLE_HEADER_BYTES + CABLE_MAX_PAYLOAD + CABLE_CRC_BYTES)

// Payload kinds. An unknown code is NOT rejected by this layer — it is handed up with its raw byte, so a
// newer daemon talking to older firmware is a visible mismatch rather than a silently swallowed message.
#define CABLE_TYPE_JSON 0x01   // UTF-8 JSON object with a "t" discriminator — the vocabulary
#define CABLE_TYPE_PCM  0x02   // one chunk of 16-bit mono PCM, device → daemon, during a voice turn
#define CABLE_TYPE_FW   0x03   // one slice of a firmware image, daemon → device only
#define CABLE_TYPE_LOG  0x04   // one ESP_LOG line, device → daemon, raw bytes (no JSON escaping)
#define CABLE_TYPE_PET  0x05   // one slice of a custom pet pack (HPET), daemon → device only

// CRC-16/CCITT-FALSE — poly 0x1021, init 0xFFFF, no reflection, no final xor.
//
// Named exactly because several 16-bit CRCs share the 0x1021 polynomial and differ only in init or
// reflection; the published check value for "123456789" is 0x29B1, which both test suites assert.
uint16_t cable_crc16(const uint8_t *data, size_t len);

// Write a frame carrying `payload` into `out`.
//
// Returns the frame length, or -1 when the payload is over CABLE_MAX_PAYLOAD or `out_cap` is too small.
// Failing here rather than truncating is deliberate: an oversized message is a bug on this side, and the
// far end could only ever report it as noise.
int cable_frame_encode(uint8_t type, const uint8_t *payload, size_t payload_len,
                       uint8_t *out, size_t out_cap);

// Called once per decoded frame. `payload` points into the decoder's own buffer and is only valid for the
// duration of the call — copy anything that must outlive it.
typedef void (*cable_frame_cb)(uint8_t version, uint8_t type,
                               const uint8_t *payload, size_t payload_len,
                               void *ctx);

// Reassembles frames from a byte stream that may start anywhere and contain anything.
//
// The buffer is a fixed array rather than a heap allocation: this runs on a device where a failed malloc
// mid-session is a worse outcome than a known 8 KB of BSS, and the ceiling is already fixed by
// CABLE_MAX_PAYLOAD.
typedef struct {
    uint8_t  buf[CABLE_MAX_FRAME];
    size_t   len;
    // The RATE is what matters: a handful of discarded bytes at every boot is the bootloader's parting
    // words and is expected, while a steady trickle during a session means the two sides disagree about
    // the format or the cable is bad. Those are very different problems and look identical without a
    // count.
    uint32_t corrupt_frames;
    uint32_t discarded_bytes;
} cable_decoder_t;

void cable_decoder_init(cable_decoder_t *d);

// Forget any partial frame. Call when the link is reopened: leftover bytes belong to a session that has
// ended, and carrying them across would put a stale half-frame in front of the next real one.
void cable_decoder_reset(cable_decoder_t *d);

// Feed `n` bytes and emit every frame they complete, in order.
//
// Never fails: everything arriving on this port is untrusted, and the only useful response to a byte that
// makes no sense is to step over it.
void cable_decoder_feed(cable_decoder_t *d, const uint8_t *data, size_t n,
                        cable_frame_cb cb, void *ctx);
