// Generated from store/browse-categories.json by store/tools/presentation.mjs.
// Run that generator after changing the taxonomy; do not edit this file.
const storeCategoryDomains = <String, Set<String>>{
  'Coding': {'Code', 'Compute', 'Web', 'Security'},
  'Design': {'3D', 'CAD', 'Architecture', 'Diagrams', 'Design', 'Original art'},
  'Engineering': {'PCB', 'Circuits', 'Chips', 'Fabrication', 'Firmware', 'Automation', 'Home automation'},
  'Media': {'Video', 'Math animation', 'Generative media'},
  'Music': {'Music', 'Audio'},
  'Productivity': {'Documents', 'Slides', 'Productivity'},
  'Science & Data': {'Science', 'Data', 'Notebooks', 'Chemistry', 'Quantum', 'GIS'},
  'Simulation': {'Simulation', 'Robotics'},
  'Games': {'Games'},
  'Research': {'Research', 'Decisions'},
  'Local AI': {'Local AI'},
};
