//! tmux 3.5a's options (options-table.c): every name, its scope and its type. Generated from
//! tmux's source; the defaults are tests/fixtures/tmux-3.5a-options.txt, as `tmux -f /dev/null`
//! prints them (`show -s`, `show -g`, `show -gw`).

use super::{Kind, Opt, Scope};

pub static TABLE: &[Opt] = &[
    Opt { name: "backspace", scope: Scope::Server, pane: false, kind: Kind::Key, array: false },
    Opt { name: "buffer-limit", scope: Scope::Server, pane: false, kind: Kind::Number(1, i32::MAX as i64), array: false },
    Opt { name: "command-alias", scope: Scope::Server, pane: false, kind: Kind::String, array: true },
    Opt { name: "copy-command", scope: Scope::Server, pane: false, kind: Kind::String, array: false },
    Opt { name: "cursor-colour", scope: Scope::Window, pane: true, kind: Kind::Colour, array: false },
    Opt { name: "cursor-style", scope: Scope::Window, pane: true, kind: Kind::Choice(&["default", "blinking-block", "block", "blinking-underline", "underline", "blinking-bar", "bar"]), array: false },
    Opt { name: "default-terminal", scope: Scope::Server, pane: false, kind: Kind::String, array: false },
    Opt { name: "editor", scope: Scope::Server, pane: false, kind: Kind::String, array: false },
    Opt { name: "escape-time", scope: Scope::Server, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "exit-empty", scope: Scope::Server, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "exit-unattached", scope: Scope::Server, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "extended-keys", scope: Scope::Server, pane: false, kind: Kind::Choice(&["off", "on", "always"]), array: false },
    Opt { name: "extended-keys-format", scope: Scope::Server, pane: false, kind: Kind::Choice(&["csi-u", "xterm"]), array: false },
    Opt { name: "focus-events", scope: Scope::Server, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "history-file", scope: Scope::Server, pane: false, kind: Kind::String, array: false },
    Opt { name: "menu-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "menu-selected-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "menu-border-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "menu-border-lines", scope: Scope::Window, pane: false, kind: Kind::Choice(&["single", "double", "heavy", "simple", "rounded", "padded", "none"]), array: false },
    Opt { name: "message-limit", scope: Scope::Server, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "prefix-timeout", scope: Scope::Server, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "prompt-history-limit", scope: Scope::Server, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "set-clipboard", scope: Scope::Server, pane: false, kind: Kind::Choice(&["off", "external", "on"]), array: false },
    Opt { name: "terminal-overrides", scope: Scope::Server, pane: false, kind: Kind::String, array: true },
    Opt { name: "terminal-features", scope: Scope::Server, pane: false, kind: Kind::String, array: true },
    Opt { name: "user-keys", scope: Scope::Server, pane: false, kind: Kind::String, array: true },
    Opt { name: "activity-action", scope: Scope::Session, pane: false, kind: Kind::Choice(&["none", "any", "current", "other"]), array: false },
    Opt { name: "assume-paste-time", scope: Scope::Session, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "base-index", scope: Scope::Session, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "bell-action", scope: Scope::Session, pane: false, kind: Kind::Choice(&["none", "any", "current", "other"]), array: false },
    Opt { name: "default-command", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "default-shell", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "default-size", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "destroy-unattached", scope: Scope::Session, pane: false, kind: Kind::Choice(&["off", "on", "keep-last", "keep-group"]), array: false },
    Opt { name: "detach-on-destroy", scope: Scope::Session, pane: false, kind: Kind::Choice(&["off", "on", "no-detached", "previous", "next"]), array: false },
    Opt { name: "display-panes-active-colour", scope: Scope::Session, pane: false, kind: Kind::Colour, array: false },
    Opt { name: "display-panes-colour", scope: Scope::Session, pane: false, kind: Kind::Colour, array: false },
    Opt { name: "display-panes-time", scope: Scope::Session, pane: false, kind: Kind::Number(1, i32::MAX as i64), array: false },
    Opt { name: "display-time", scope: Scope::Session, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "history-limit", scope: Scope::Session, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "key-table", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "lock-after-time", scope: Scope::Session, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "lock-command", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "message-command-style", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "message-line", scope: Scope::Session, pane: false, kind: Kind::Choice(&["0", "1", "2", "3", "4"]), array: false },
    Opt { name: "message-style", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "mouse", scope: Scope::Session, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "prefix", scope: Scope::Session, pane: false, kind: Kind::Key, array: false },
    Opt { name: "prefix2", scope: Scope::Session, pane: false, kind: Kind::Key, array: false },
    Opt { name: "renumber-windows", scope: Scope::Session, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "repeat-time", scope: Scope::Session, pane: false, kind: Kind::Number(0, 32767), array: false },
    Opt { name: "set-titles", scope: Scope::Session, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "set-titles-string", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "silence-action", scope: Scope::Session, pane: false, kind: Kind::Choice(&["none", "any", "current", "other"]), array: false },
    Opt { name: "status", scope: Scope::Session, pane: false, kind: Kind::Choice(&["off", "on", "2", "3", "4", "5"]), array: false },
    Opt { name: "status-bg", scope: Scope::Session, pane: false, kind: Kind::Colour, array: false },
    Opt { name: "status-fg", scope: Scope::Session, pane: false, kind: Kind::Colour, array: false },
    Opt { name: "status-format", scope: Scope::Session, pane: false, kind: Kind::String, array: true },
    Opt { name: "status-interval", scope: Scope::Session, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "status-justify", scope: Scope::Session, pane: false, kind: Kind::Choice(&["left", "centre", "right", "absolute-centre"]), array: false },
    Opt { name: "status-keys", scope: Scope::Session, pane: false, kind: Kind::Choice(&["emacs", "vi"]), array: false },
    Opt { name: "status-left", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "status-left-length", scope: Scope::Session, pane: false, kind: Kind::Number(0, 32767), array: false },
    Opt { name: "status-left-style", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "status-position", scope: Scope::Session, pane: false, kind: Kind::Choice(&["top", "bottom"]), array: false },
    Opt { name: "status-right", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "status-right-length", scope: Scope::Session, pane: false, kind: Kind::Number(0, 32767), array: false },
    Opt { name: "status-right-style", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "status-style", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "update-environment", scope: Scope::Session, pane: false, kind: Kind::String, array: true },
    Opt { name: "visual-activity", scope: Scope::Session, pane: false, kind: Kind::Choice(&["off", "on", "both"]), array: false },
    Opt { name: "visual-bell", scope: Scope::Session, pane: false, kind: Kind::Choice(&["off", "on", "both"]), array: false },
    Opt { name: "visual-silence", scope: Scope::Session, pane: false, kind: Kind::Choice(&["off", "on", "both"]), array: false },
    Opt { name: "word-separators", scope: Scope::Session, pane: false, kind: Kind::String, array: false },
    Opt { name: "aggressive-resize", scope: Scope::Window, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "allow-passthrough", scope: Scope::Window, pane: true, kind: Kind::Choice(&["off", "on", "all"]), array: false },
    Opt { name: "allow-rename", scope: Scope::Window, pane: true, kind: Kind::Flag, array: false },
    Opt { name: "allow-set-title", scope: Scope::Window, pane: true, kind: Kind::Flag, array: false },
    Opt { name: "alternate-screen", scope: Scope::Window, pane: true, kind: Kind::Flag, array: false },
    Opt { name: "automatic-rename", scope: Scope::Window, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "automatic-rename-format", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "clock-mode-colour", scope: Scope::Window, pane: false, kind: Kind::Colour, array: false },
    Opt { name: "clock-mode-style", scope: Scope::Window, pane: false, kind: Kind::Choice(&["12", "24"]), array: false },
    Opt { name: "copy-mode-match-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "copy-mode-current-match-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "copy-mode-mark-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "fill-character", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "main-pane-height", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "main-pane-width", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "mode-keys", scope: Scope::Window, pane: false, kind: Kind::Choice(&["emacs", "vi"]), array: false },
    Opt { name: "mode-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "monitor-activity", scope: Scope::Window, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "monitor-bell", scope: Scope::Window, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "monitor-silence", scope: Scope::Window, pane: false, kind: Kind::Number(0, i32::MAX as i64), array: false },
    Opt { name: "other-pane-height", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "other-pane-width", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "pane-active-border-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "pane-base-index", scope: Scope::Window, pane: false, kind: Kind::Number(0, 65535), array: false },
    Opt { name: "pane-border-format", scope: Scope::Window, pane: true, kind: Kind::String, array: false },
    Opt { name: "pane-border-indicators", scope: Scope::Window, pane: false, kind: Kind::Choice(&["off", "colour", "arrows", "both"]), array: false },
    Opt { name: "pane-border-lines", scope: Scope::Window, pane: false, kind: Kind::Choice(&["single", "double", "heavy", "simple", "number"]), array: false },
    Opt { name: "pane-border-status", scope: Scope::Window, pane: false, kind: Kind::Choice(&["off", "top", "bottom"]), array: false },
    Opt { name: "pane-border-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "pane-colours", scope: Scope::Window, pane: true, kind: Kind::Colour, array: true },
    Opt { name: "popup-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "popup-border-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "popup-border-lines", scope: Scope::Window, pane: false, kind: Kind::Choice(&["single", "double", "heavy", "simple", "rounded", "padded", "none"]), array: false },
    Opt { name: "remain-on-exit", scope: Scope::Window, pane: true, kind: Kind::Choice(&["off", "on", "failed"]), array: false },
    Opt { name: "remain-on-exit-format", scope: Scope::Window, pane: true, kind: Kind::String, array: false },
    Opt { name: "scroll-on-clear", scope: Scope::Window, pane: true, kind: Kind::Flag, array: false },
    Opt { name: "synchronize-panes", scope: Scope::Window, pane: true, kind: Kind::Flag, array: false },
    Opt { name: "window-active-style", scope: Scope::Window, pane: true, kind: Kind::String, array: false },
    Opt { name: "window-size", scope: Scope::Window, pane: false, kind: Kind::Choice(&["largest", "smallest", "manual", "latest"]), array: false },
    Opt { name: "window-style", scope: Scope::Window, pane: true, kind: Kind::String, array: false },
    Opt { name: "window-status-activity-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "window-status-bell-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "window-status-current-format", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "window-status-current-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "window-status-format", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "window-status-last-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "window-status-separator", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "window-status-style", scope: Scope::Window, pane: false, kind: Kind::String, array: false },
    Opt { name: "wrap-search", scope: Scope::Window, pane: false, kind: Kind::Flag, array: false },
    Opt { name: "xterm-keys", scope: Scope::Window, pane: false, kind: Kind::Flag, array: false },
];

/// tmux 3.5a's hooks (OPTIONS_TABLE_HOOK, _PANE_HOOK, _WINDOW_HOOK), in its table's order after
/// the options: arrays of commands, empty by default.
pub static HOOKS: &[Opt] = &[
    Opt { name: "after-bind-key", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-capture-pane", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-copy-mode", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-display-message", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-display-panes", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-kill-pane", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-list-buffers", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-list-clients", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-list-keys", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-list-panes", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-list-sessions", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-list-windows", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-load-buffer", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-lock-server", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-new-session", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-new-window", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-paste-buffer", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-pipe-pane", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-queue", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-refresh-client", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-rename-session", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-rename-window", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-resize-pane", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-resize-window", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-save-buffer", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-select-layout", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-select-pane", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-select-window", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-send-keys", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-set-buffer", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-set-environment", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-set-hook", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-set-option", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-show-environment", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-show-messages", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-show-options", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-split-window", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "after-unbind-key", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "alert-activity", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "alert-bell", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "alert-silence", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "client-active", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "client-attached", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "client-detached", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "client-focus-in", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "client-focus-out", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "client-resized", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "client-session-changed", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "command-error", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "pane-died", scope: Scope::Window, pane: true, kind: Kind::Command, array: true },
    Opt { name: "pane-exited", scope: Scope::Window, pane: true, kind: Kind::Command, array: true },
    Opt { name: "pane-focus-in", scope: Scope::Window, pane: true, kind: Kind::Command, array: true },
    Opt { name: "pane-focus-out", scope: Scope::Window, pane: true, kind: Kind::Command, array: true },
    Opt { name: "pane-mode-changed", scope: Scope::Window, pane: true, kind: Kind::Command, array: true },
    Opt { name: "pane-set-clipboard", scope: Scope::Window, pane: true, kind: Kind::Command, array: true },
    Opt { name: "pane-title-changed", scope: Scope::Window, pane: true, kind: Kind::Command, array: true },
    Opt { name: "session-closed", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "session-created", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "session-renamed", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "session-window-changed", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "window-layout-changed", scope: Scope::Window, pane: false, kind: Kind::Command, array: true },
    Opt { name: "window-linked", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "window-pane-changed", scope: Scope::Window, pane: false, kind: Kind::Command, array: true },
    Opt { name: "window-renamed", scope: Scope::Window, pane: false, kind: Kind::Command, array: true },
    Opt { name: "window-resized", scope: Scope::Window, pane: false, kind: Kind::Command, array: true },
    Opt { name: "window-unlinked", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    // hn's: a harness asks (harness-needs), ends a turn (harness-done), meets an error
    // (harness-failed) — with #{hook_harness_name} #{hook_harness_id} #{hook_harness_machine}
    // #{hook_harness_line} #{hook_harness_question}.
    Opt { name: "harness-done", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "harness-failed", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
    Opt { name: "harness-needs", scope: Scope::Session, pane: false, kind: Kind::Command, array: true },
];
