// Generated by scripts/gen_focus_faces.py. Do not edit.
#pragma once
#include "terminal.h"
extern const ht_pfont_t ht_lv_inter_20;
extern const ht_pfont_t ht_lv_inter_25;
extern const ht_pfont_t ht_lv_inter_med_26;
extern const ht_pfont_t ht_lv_inter_28;
extern const ht_pfont_t ht_lv_inter_30;
extern const ht_pfont_t ht_lv_inter_44;
extern const ht_pfont_t ht_lv_inter_36;
extern const ht_pfont_t ht_lv_inter_bold_48;
