// Generated by scripts/gen_lvgl_assets.py. Do not edit.
// Icon faces only: LVGL 9.5.0 Montserrat (MIT; fonts OFL) cut down to the bell and the close cross.
#include "terminal.h"
// montserrat_22: 2 glyphs, line 24, base 4, 128 bitmap bytes.
static const uint8_t montserrat_22_px[] = {
  8,196,0,0,0,2,201,0,159,255,64,0,0,46,255,176,255,255,244,0,2,239,255,241,
  127,255,255,64,46,255,255,144,8,255,255,246,239,255,250,0,0,143,255,255,255,255,160,0,
  0,8,255,255,255,250,0,0,0,0,159,255,255,176,0,0,0,2,239,255,255,244,0,0,
  0,46,255,255,255,255,64,0,2,239,255,253,255,255,244,0,46,255,255,160,143,255,255,64,
  223,255,250,0,8,255,255,240,223,255,160,0,0,143,255,224,46,250,0,0,0,8,255,48,
  0,48,0,0,0,0,33,0,
};
static const ht_glyph_t montserrat_22_glyphs[] = {
  {0,95,0,0,0,20},
  {0,242,16,16,0,4},
};
static const uint16_t montserrat_22_codes[] = {32,61453};
static const uint8_t montserrat_22_kl[] = {0,0};
static const uint8_t montserrat_22_kr[] = {0,0};
static const int8_t montserrat_22_kv[] = {0};
const ht_pfont_t ht_lv_montserrat_22 = {{1,0,6,24,montserrat_22_px},montserrat_22_glyphs,montserrat_22_codes,2,20,montserrat_22_kl,montserrat_22_kr,montserrat_22_kv,1,NULL};
// montserrat_14: 2 glyphs, line 16, base 3, 98 bitmap bytes.
static const uint8_t montserrat_14_px[] = {
  0,0,1,16,0,0,0,0,0,175,0,0,0,0,1,143,250,48,0,0,2,239,255,255,
  80,0,0,191,255,255,255,16,0,31,255,255,255,245,0,3,255,255,255,255,112,0,95,255,
  255,255,249,0,8,255,255,255,255,192,0,223,255,255,255,255,32,159,255,255,255,255,253,14,
  255,255,255,255,255,242,2,34,34,34,34,33,0,0,8,255,192,0,0,0,0,9,162,0,
  0,0,
};
static const ht_glyph_t montserrat_14_glyphs[] = {
  {0,60,0,0,0,13},
  {0,196,13,15,0,0},
};
static const uint16_t montserrat_14_codes[] = {32,61683};
static const uint8_t montserrat_14_kl[] = {0,0};
static const uint8_t montserrat_14_kr[] = {0,0};
static const int8_t montserrat_14_kv[] = {0};
const ht_pfont_t ht_lv_montserrat_14 = {{1,0,4,16,montserrat_14_px},montserrat_14_glyphs,montserrat_14_codes,2,13,montserrat_14_kl,montserrat_14_kr,montserrat_14_kv,1,NULL};
